### ISSUE TITLE
Request to remove the "humor" Gitub tag

### ISSUE THREAD

**Issue by schalkventer** [joaomilho/Enterprise#48]
As an aspiring Enterprise developer I can only assume this tag was added by accident.

![image](https://user-images.githubusercontent.com/14258328/76397229-6257ac80-6383-11ea-8816-bb51f0bcdc1e.png)

**Comment by joaomilho** [comment]
OH MY GOD. Some HACKER did this! These people have nothing else to do. FIXED.
