### ISSUE TITLE
How can we purchase extended support?

### ISSUE THREAD

**Issue by leriblis** [joaomilho/Enterprise#6]
Dear Enterprise™ Corporation Representer,

We believe that this language aligns well with our organization’s values and culture, however, the extended support option is an absolute must have for us. 

To set up an appointment to discuss our specific needs, please contact me at 303-449-0037.

Kindest regards,

Enterprise

**Comment by joaomilho** [comment]
Our tech sales team will be in touch shortly to present our successful Disruptive Business Cases to you.

Thank you very much for reaching out.
