### ISSUE TITLE
Remove Int, Replace Float with Money

### ISSUE THREAD

**Issue by dooreelko** [joaomilho/Enterprise#8]
Rather obviously since the purpose of the Enterprise™ solutions is to disrupt markets, the aforementioned solutions do not require any numerical values except for Money™, thus the combined universal replacement for Int and Float should be called Money.
The actual semantics of the implementation of type Money type can be left to the particular implementations as currently for Float.

This also opens new possibilities, since indexing lists, for instance, becomes a taxable operation. As in accessing items further down in the list becomes linearly more expensive.

**Comment by joaomilho** [comment]
Disruptive. Brilliant. Int and Float are the same anyway.

**Comment by jonstacks** [comment]
@dooreelko I like where this is going, but is there any way we can include a disruptive Cryto<sup>TM</sup> implementation. In contrast to the O1Type, assigning values to Cryto<sup>TM</sup> variables block until transaction fees are low enough and you get enough confirmations from the Enterprise<sup>TM</sup> block chain. How low must transaction fees be? Obviously you set it as a config value in an Enterprise<sup>TM</sup>.xml file and it get loaded somehow. A top [search result](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/save-your-site-list-to-xml-in-the-enterprise-mode-site-list-manager) reveals that this may already be an emerging enterprise trend.

**Comment by dooreelko** [comment]
@jonstacks looks like a new feature!
